export const MAC_KEYS = {
  Shift: "Shift",
  Control: "Control",
  Option: "Alt",
  Command: "Meta",
  CapsLock: "CapsLock",
  Tab: "Tab",
  Escape: "Escape",
  Enter: "Enter",
  Space: " ",
  Backspace: "Backspace",
  Delete: "Delete",
  ArrowUp: "ArrowUp",
  ArrowDown: "ArrowDown",
  ArrowLeft: "ArrowLeft",
  ArrowRight: "ArrowRight",
  Home: "Home",
  End: "End",
  PageUp: "PageUp",
  PageDown: "PageDown",
};
